onyxlog/estoque/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers

from views.index import *
from views.endereco import *
from views.saldo import *

router = routers.DefaultRouter()
router.register(r'saldo',SaldoViewSet)

urlpatterns = patterns('',
    url(r'^$', Index.as_view(), name='estoque.estoque_index'),
    
    # endereco
    url(r'^endereco/api/fit/$', ApiEnderecoFit.as_view(),name='endereco.api_endereco_fit'),

    url(r'^endereco/data/$', EnderecoData.as_view(),name='estoque.list_json_endereco'),
    url(r'^endereco/formulario/$', EnderecoCreateForm.as_view(),name='estoque.add_endereco'),
    url(r'^endereco/(?P<pk>\d+)/$', EnderecoUpdateForm.as_view(),name='estoque.change_endereco'),
    url(r'^endereco/remove/(?P<pk>\d+)/$', EnderecoDelete.as_view(),name='estoque.delete_endereco'),
    url(r'^endereco/$', EnderecoList.as_view(), name='estoque.list_endereco'),

    # saldo
    url(r'^saldo/data/$', SaldoData.as_view(),name='estoque.list_json_saldo'),
    url(r'^saldo/formulario/$', SaldoCreateForm.as_view(),name='estoque.add_saldo'),
    url(r'^saldo/(?P<pk>\d+)/$', SaldoUpdateForm.as_view(),name='estoque.change_saldo'),
    url(r'^saldo/remove/(?P<pk>\d+)/$', SaldoDelete.as_view(),name='estoque.delete_saldo'),
    url(r'^saldo/$', SaldoList.as_view(), name='estoque.list_saldo'),

    url(r'^endereco/automatico/$', EnderecoAuto.as_view(), name='estoque.endereco_auto'),

    # api
    url(r'^api/', include(router.urls))
    
)

onyxlog/urls.py
from django.views.generic import RedirectView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('onyxlog.core.urls'),name="App-Principal"),

    url(r'^core/', include('onyxlog.core.urls')),
    url(r'^acesso/', include('onyxlog.acesso.urls')),
    url(r'^cadastros/', include('onyxlog.cadastros.urls')),
    url(r'^etiquetas/', include('onyxlog.etiqueta.urls')),
    url(r'^estoque/', include('onyxlog.estoque.urls')),
    url(r'^portaria/', include('onyxlog.portaria.urls')),
    # Examples:
    # url(r'^$', 'onyxlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

handler403 = 'onyxlog.core.views.core.error403'
handler404 = 'onyxlog.core.views.core.error404'
handler500 = 'onyxlog.core.views.core.error500'

onyxlog/estoque/models/endereco.py
# -*- coding: utf-8 -*-
from django.db import models
from rest_framework import serializers
from ...cadastros.models.planta import Planta, PlantaSerializer

class Endereco(models.Model):
    """
    Model do cadastro de enderecos
    """
    planta = models.ForeignKey(Planta, verbose_name='Planta', blank=True, null=True, on_delete=models.PROTECT)
    codigo = models.CharField(verbose_name='Código', max_length=15, blank=False, null=False, default='')

    def __unicode__(self):
        return self.codigo

    class Meta:
        app_label = 'estoque'

class EnderecoSerializer(serializers.HyperlinkedModelSerializer):
    """
    Serializador
    """
    planta = PlantaSerializer()

    class Meta:
        model = Endereco
        fields = ('planta', 'codigo', )

onyxlog/estoque/models/saldo.py
# -*- coding: utf-8 -*-
from django.db import models
from django.shortcuts import get_object_or_404
from rest_framework import serializers
from rest_framework.utils.serializer_helpers import ReturnDict

from ...cadastros.models.produto import Produto, ProdutoSerializer
from .endereco import Endereco, EnderecoSerializer

class Saldo(models.Model):
    """
    Model para saldo de produtos
    """
    endereco = models.ForeignKey(Endereco, verbose_name='Endereco', blank=False, null=False, on_delete=models.PROTECT)
    produto  = models.ForeignKey(Produto , verbose_name='Produto' , blank=False, null=False, on_delete=models.PROTECT)
    quant    = models.DecimalField(verbose_name="Quantidade", blank=False, null=False, max_digits=19, decimal_places=4)

    def __unicode__(self):
        return self.endereco.codigo + ' - ' + self.produto.codigo + '::' + str(quant)

    class Meta:
        app_label = 'estoque'

class SaldoSerializer(serializers.HyperlinkedModelSerializer):
    """
    Serializador do saldo de produtos e endereços
    """
    endereco = EnderecoSerializer()
    produto = ProdutoSerializer()

    class Meta:
        model = Saldo
        fields = ('endereco', 'produto', 'quant', )

class SaldoCustomSerializer(serializers.Serializer):
    endereco = serializers.CharField(max_length=15)
    produto  = serializers.CharField(max_length=15)
    quant    = serializers.DecimalField(max_digits=19, decimal_places=4)

    def create(self, validated_data):
        enderecos = Endereco.objects.filter(codigo=validated_data.get('endereco'))
        produtos  = Produto.objects.filter(codigo=validated_data.get('produto' ))
        if not enderecos:
            raise serializers.ValidationError('Endereco invalido %s.' % (validated_data.get('endereco')))
        elif not produtos:
            raise serializers.ValidationError('Produto invalido %s.' % (validated_data.get('produto')))

        endereco = enderecos[0]
        produto  = produtos[0]
        quant    = validated_data.get('quant')

        saldos = Saldo.objects.filter(endereco=endereco, produto=produto)

        if saldos:
            saldo = saldos[0]
            saldo.quant = quant
        else:
            saldo = Saldo(endereco=endereco, produto=produto, quant=quant)

        saldo.save()

        return saldo

onyxlog/estoque/forms/enderecoautoform.py
# -*- coding: ISO-8859-1 -*-
from django import forms

from ...cadastros.models.planta import Planta

class EtiquetaAutoForm(forms.Form):
    planta = forms.ModelChoiceField(queryset=Planta.objects.all(), label="Planta")
    zona_de = forms.CharField(label="Da Zona", max_length=3)
    zona_ate = forms.CharField(label="Até a Zona", max_length=3)
    instalacao_de = forms.CharField(label="Da Instalação", max_length=5)
    instalacao_ate = forms.CharField(label="Até a Instalação", max_length=5)
    rua_de = forms.CharField(label="Da Rua", max_length=3)
    rua_ate = forms.CharField(label="Até a Rua", max_length=3)
    estante_de = forms.CharField(label="Da Estante", max_length=3)
    estante_ate = forms.CharField(label="Até a Estante", max_length=3)
    prateleira_de = forms.CharField(label="Da Prateleira", max_length=3)
    prateleira_ate = forms.CharField(label="Até a Prateleira", max_length=3)

onyxlog/estoque/views/endereco.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Q
from django.shortcuts import redirect
from django.http import Http404

from ...core.base.core_base_datatable import CoreBaseDatatableView
from ...core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from ...core.mixins.core_mixin_login import CoreMixinLoginRequired
from ...core.mixins.core_mixin_json import JSONResponseMixin

from ..models.endereco import Endereco

class EnderecoList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista
    """
    template_name = 'endereco_list.html'
    
class EnderecoData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista
    """
    model = Endereco
    columns = ['planta', 'codigo', 'buttons', ]
    order_columns = ['codigo',]
    max_display_length = 500
    url_base_form = '/estoque/endereco/'

    def render_column(self, row, column):
        if column == 'planta':
            sReturn = row.planta.codigo + ' - ' + row.planta.nome if row.planta else ''
            return sReturn
        else:
            return super(EnderecoData, self).render_column(row, column)
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(codigo__istartswith=part)|Q(planta__codigo__istartswith=part)|Q(planta__nome__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)

        return qs

class EnderecoCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Endereco
    template_name = 'endereco_form.html'
    success_url = '/'

class EnderecoUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Endereco
    template_name = 'endereco_form.html'
    success_url = '/'

class EnderecoDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = Endereco
    success_url = '/estoque/endereco/'

class EnderecoAuto(CoreMixinLoginRequired, TemplateView):
    """
    View para geração automática
    """
    template_name = 'endereco_auto.html'

class ApiEnderecoFit(CoreMixinLoginRequired, JSONResponseMixin, TemplateView):
    """
    Retorna em json os enderecos
    """
    def get(self, request, *args, **kwargs):
        qs = Endereco.objects.all()
        data = []
        
        for item in qs:
            data.append({
                "id": item.pk,
                "codigo": item.codigo,
            })

        context = data
        
        return self.render_to_response(context)

onyxlog/estoque/views/index.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic import TemplateView

from ...core.mixins.core_mixin_login import CoreMixinLoginRequired

class Index(CoreMixinLoginRequired, TemplateView):
    template_name = "estoque_menu.html"

onyxlog/estoque/views/saldo.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models import Q
from rest_framework import viewsets

from ...core.base.core_base_datatable import CoreBaseDatatableView
from ...core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from ...core.mixins.core_mixin_login import CoreMixinLoginRequired

from ..models.saldo import Saldo, SaldoSerializer, SaldoCustomSerializer

class SaldoList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista
    """
    template_name = 'saldo_list.html'
    
class SaldoData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista
    """
    model = Saldo
    columns = ['endereco', 'produto', 'descricao', 'quant', 'buttons', ]
    order_columns = ['endereco', 'produto', ]
    max_display_length = 500
    url_base_form = '/estoque/saldo/'

    def render_column(self, row, column):
        if column == 'endereco':
            sReturn = row.endereco.codigo
            return sReturn
        elif column == 'produto':
            sReturn = row.produto.codigo
            return sReturn
        elif column == 'descricao':
            sReturn = row.produto.desc
            return sReturn
        else:
            return super(SaldoData, self).render_column(row, column)
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(endereco__codigo__istartswith=part)|Q(produto__codigo__istartswith=part)|Q(produto__desc__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)

        return qs

class SaldoCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Saldo
    template_name = 'saldo_form.html'
    success_url = '/'

class SaldoUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Saldo
    template_name = 'saldo_form.html'
    success_url = '/'

class SaldoDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = Saldo
    success_url = '/estoque/saldos/'

class SaldoViewSet(viewsets.ModelViewSet):
    queryset = Saldo.objects.all()
    serializer_class = SaldoCustomSerializer

onyxlog/estoque/templates/endereco_auto.html
{% extends "base_form.html"%}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap_toolkit %}

{% block title %}Endereços{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Estoque" "/estoque/" %}
    {% breadcrumb "Endereço" "/estoque/endereco/" %}
    
    {% if object %}
        {% breadcrumb form.codigo.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}


{% block formRender %}
    <div class="row">
        <div class="col-lg-6 ">
            <div class="response_form alert alert-dismissable"><span></span></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 top-buffer-10">
            <form class="form-horizontal" redirect_data="{% url 'estoque.list_endereco' %}" method="post" action="{{ request.get_full_path }}" id="formEndereco" onSubmit="return false;">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                {% block button %}
                    {{ block.super }}
                {% endblock %}
            </form>
        </div>
    </div>
{% endblock %}

onyxlog/estoque/templates/endereco_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Estoque" "#" %}
    {% breadcrumb "Endereço" "/estoque/endereco/" %}
    
    {% if object %}
        {% breadcrumb form.codigo.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}

{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-bookmark"></i>
    <h3>{% block title %}Endereços{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'estoque.list_endereco' %}{% endblock %}

onyxlog/estoque/templates/endereco_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Estoque" "#" %}
    {% breadcrumb "Endereço" "/estoque/endereco/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-bookmark"></i>
    <h3>{% block title %}Endereços{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table  table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'estoque.list_json_endereco' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="50%" class="no_sort">Planta</th>
                <th width="40%">Código</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}

onyxlog/estoque/templates/saldo_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Estoque" "#" %}
    {% breadcrumb "Saldos" "/estoque/endereco/" %}
    {% breadcrumb form.quant.value "/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-bookmark"></i>
    <h3>{% block title %}Saldos{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'estoque.list_saldo' %}{% endblock %}
{% block jsExtra %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.combobox.js' %}" ></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#id_endereco').combobox();
            $('#id_produto').combobox();
        });
    </script>
{% endblock %}

onyxlog/estoque/templates/saldo_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Estoque" "#" %}
    {% breadcrumb "Saldos" "/estoque/saldos/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-th-large"></i>
    <h3>{% block title %}Saldos{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table  table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'estoque.list_json_saldo' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="15%" class="no_sort">Endereço</th>
                <th width="15%" class="no_sort">Produto</th>
                <th width="0%" class="no_sort">Descrição</th>
                <th width="20%" class="no_sort">Quant</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}