onyxlog/portaria/urls.py
from django.conf.urls import patterns, include, url

from views.index import *
from views.movimentovisitante import *
from views.movimentoveiculo import *
from views.motivo import *
from views.report import *


urlpatterns = patterns('',
    url(r'^$', PortariaIndex.as_view(), name='portaria.portaria_index'),
    
    # movimento de visitantes
    url(r'^movimento/visitante/data/$', MovimentoVisitanteData.as_view(),name='portaria.list_json_movimentovisitante'),
    url(r'^movimento/visitante/formulario/$', MovimentoVisitanteCreateForm.as_view(),name='portaria.add_movimentovisitante'),
    url(r'^movimento/visitante/(?P<pk>\d+)/$', MovimentoVisitanteUpdateForm.as_view(),name='portaria.change_movimentovisitante'),
    url(r'^movimento/visitante/remove/(?P<pk>\d+)/$', MovimentoVisitanteDelete.as_view(),name='portaria.delete_movimentovisitante'),
    url(r'^movimento/visitante/$', MovimentoVisitanteList.as_view(), name='portaria.list_movimentovisitante'),
    url(r'^movimento/visitante/pdf/', 'onyxlog.portaria.views.movimentovisitante.pdfEtiquetaVisitante', name='portaria.etiqueta_visitante_pdf'),

    url(r'^movimento/visitante/api/fit/$', ApiVisitanteFit.as_view(),name='portaria.api_visitante_fit'),
    url(r'^movimento/visitante/api/(?P<cpf>\d+)/$', ApiVisitanteDetail.as_view(),name='portaria.api_visitante_detail'),


    # movimento de veiculos
    url(r'^movimento/veiculo/data/$', MovimentoVeiculoData.as_view(),name='portaria.list_json_movimentoveiculo'),
    url(r'^movimento/veiculo/formulario/$', MovimentoVeiculoCreateForm.as_view(),name='portaria.add_movimentoveiculo'),
    url(r'^movimento/veiculo/(?P<pk>\d+)/$', MovimentoVeiculoUpdateForm.as_view(),name='portaria.change_movimentoveiculo'),
    url(r'^movimento/veiculo/remove/(?P<pk>\d+)/$', MovimentoVeiculoDelete.as_view(),name='portaria.delete_movimentoveiculo'),
    url(r'^movimento/veiculo/$', MovimentoVeiculoList.as_view(), name='portaria.list_movimentoveiculo'),

    url(r'^movimento/veiculo/api/(?P<placa>[\w_-]+)/$', ApiVeiculoDetail.as_view(),name='portaria.api_veiculo_detail'),

    # motivos
    url(r'^motivo/data/$', MotivoData.as_view(),name='portaria.list_json_motivo'),
    url(r'^motivo/formulario/$', MotivoCreateForm.as_view(),name='portaria.add_motivo'),
    url(r'^motivo/(?P<pk>\d+)/$', MotivoUpdateForm.as_view(),name='portaria.change_motivo'),
    url(r'^motivo/remove/(?P<pk>\d+)/$', MotivoDelete.as_view(),name='portaria.delete_motivo'),
    url(r'^motivo/$', MotivoList.as_view(), name='portaria.list_motivo'),

    # relatorio
    url(r'^report/$', ReportView.as_view(),name='portaria.report'),
)

onyxlog/urls.py
from django.views.generic import RedirectView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('onyxlog.core.urls'),name="App-Principal"),

    url(r'^core/', include('onyxlog.core.urls')),
    url(r'^acesso/', include('onyxlog.acesso.urls')),
    url(r'^cadastros/', include('onyxlog.cadastros.urls')),
    url(r'^etiquetas/', include('onyxlog.etiqueta.urls')),
    url(r'^estoque/', include('onyxlog.estoque.urls')),
    url(r'^portaria/', include('onyxlog.portaria.urls')),
    # Examples:
    # url(r'^$', 'onyxlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

handler403 = 'onyxlog.core.views.core.error403'
handler404 = 'onyxlog.core.views.core.error404'
handler500 = 'onyxlog.core.views.core.error500'

onyxlog/portaria/models/motivo.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from rest_framework import serializers

class Motivo(models.Model):
    """
    Model do cadastro de motivos de visita
    """
    nome     = models.CharField(verbose_name=_('Nome'), max_length=60, blank=False, null=False)

    def __unicode__(self):
        return self.nome

    class Meta:
        app_label = 'portaria'

class MotivoSerializer(serializers.HyperlinkedModelSerializer):
    """
    Serializador
    """
    class Meta:
        model = Motivo
        fields = ('nome', )

onyxlog/portaria/models/movimento.py
# -*- coding: ISO-8859-1 -*-
import datetime
from django.db import models

class Movimento(models.Model):
    """
    Model dos movimentos de entrada e saída de portaria
    """

    entrada = models.DateField(
        verbose_name="Entrada",
        blank=True,
        null=False    
    )

    entrada_hora = models.TimeField(
        verbose_name="Hora Entrada",
        blank=True,
        null=True,    
    )

    saida = models.DateField(
        verbose_name="Saída",
        blank=True,
        null=True    
    )

    saida_hora = models.TimeField(
        verbose_name="Hora Saída",
        blank=True,
        null=True    
    )

    liberado_por = models.CharField(
        verbose_name="Liberado por",
        help_text="Usuário que liberou a entrada.",
        max_length=80,
        blank=True,
        null=True
    )

    obs = models.TextField(
        verbose_name="Obs",
        blank=True,
        null=True
    )

    codigo = models.CharField(
        verbose_name="Código",
        max_length=20,
        blank=True,
        null=False,
        default=''
    )

    motivo = models.ForeignKey(
        'portaria.Motivo',
        verbose_name="Motivo da Visita",
        blank=False,
        null=True,
        on_delete=models.PROTECT
    )

    planta = models.ForeignKey(
        'cadastros.Planta',
        verbose_name="Planta de Operação",
        blank=False,
        null=False,
        default=1
    )

    def save(self, *args, **kwargs):
        if not self.pk:
            if not self.entrada:
                self.entrada = datetime.datetime.now()
                self.entrada_hora = datetime.datetime.now().time()

            self.codigo = str(self.entrada.year) + str(self.entrada.month) + str(self.entrada.day)
            self.codigo = self.codigo + str(self.entrada_hora.hour) + str(self.entrada_hora.minute) + str(self.entrada_hora.second)
        elif not self.saida:
            self.saida = datetime.datetime.now()
            self.saida_hora = datetime.datetime.now().time()
            self.save()

        super(Movimento, self).save(*args, **kwargs)

    class Meta:
        app_label="portaria"

onyxlog/portaria/models/movimentoveiculo.py
# -*- coding: ISO-8859-1 -*-
from django.db import models
from rest_framework import serializers

from .movimento import Movimento

class MovimentoVeiculo(Movimento):
    """
    Movimentos de entrada e saída de veículos
    """

    placa = models.CharField(
        verbose_name="Placa",
        max_length=7,
        blank=False,
        null=False,
    )

    veiculo = models.CharField(
        verbose_name="Veículo",
        help_text="Ex. Fiat Pálio, Gol, Caminhão Scannia.",
        max_length=60,
        blank=False,
        null=False,
    )


    cor = models.CharField(
        verbose_name="Cor",
        help_text="Descreva a cor do veículo.",
        max_length=30,
        blank=False,
        null=False,
    )

    nota = models.CharField(
        verbose_name="Nota Fiscal",
        help_text="Nota fiscal que está sendo entregue.",
        max_length=20,
        blank=True,
        null=True
    )

    fornecedor = models.CharField(
        verbose_name="Fornecedor",
        max_length=80,
        blank=True,
        null=True
    )

    class Meta:
        app_label="portaria"

class MovimentoVeiculoSerializer(serializers.HyperlinkedModelSerializer):
    """
    Serializador
    """

    class Meta:
        model = MovimentoVeiculo
        fields = ('tipo', 'data', 'veiculo', 'placa', 'cor', 'liberado_por', )
        

onyxlog/portaria/models/movimentovisitante.py
# -*- coding: ISO-8859-1 -*-
from django.db import models
from rest_framework import serializers

from .movimento import Movimento
from .movimentoveiculo import MovimentoVeiculoSerializer

class MovimentoVisitante(Movimento):
    """
    Movimentos de entrada e saída de visitantes
    """

    cpf = models.CharField(
        verbose_name="CPF",
        help_text="Utilize apenas números. Não utilize caracteres como ., - ou /",
        max_length=11,
        blank=False,
        null=False,
        default=''
    )

    nome = models.CharField(
        verbose_name="Nome",
        max_length=100,
        blank=False,
        null=False
    )

    empresa = models.CharField(
        verbose_name="Empresa",
        max_length=60,
        blank=True,
        null=True
    )

    veiculo = models.ForeignKey(
        'portaria.MovimentoVeiculo',
        verbose_name="Veículo",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="ocupantes"
    )

    class Meta:
        app_label="portaria"

class MovimentoVisitanteSerializer(serializers.HyperlinkedModelSerializer):
    """
    Serializador
    """

    class Meta:
        model = MovimentoVisitante
        fields = ('tipo', 'data', 'cpf', 'nome', 'empresa', 'liberado_por', )

onyxlog/portaria/forms/reportform.py
# -*- coding: utf-8 -*-

from django import forms

class ReportForm(forms.Form):
    data_inicio = forms.DateField(label="Do dia")
    data_fim = forms.DateField(label=u"Até o dia")

    CHOICE_FILTER = (
        ('1',u'Veículos e Visitantes'),
        ('2',u'Apenas Veículos'),
        ('3',u'Apenas Visitantes'),
    )
    filtro = forms.ChoiceField(choices=CHOICE_FILTER)
    nota = forms.CharField(max_length=30, required=False)
    placa = forms.CharField(max_length=30, required=False)
    cpf = forms.CharField(max_length=20, required=False)
    

onyxlog/portaria/forms/veiculo_form.py
# -*- coding: ISO-8859-1 -*-
import datetime
from django import forms

from ..models.movimentoveiculo import MovimentoVeiculo

class MovimentoVeiculoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            request = kwargs.pop('request')
        else:
            request = None

        super(MovimentoVeiculoForm, self).__init__(*args, **kwargs)

        if not request.user.is_superuser:
            self.fields['entrada'].widget.attrs['disabled'] = True
            self.fields['entrada_hora'].widget.attrs['disabled'] = True
            self.fields['saida'].widget.attrs['disabled'] = True
            self.fields['saida_hora'].widget.attrs['disabled'] = True

        if request:
            if hasattr(request.user, 'perfil'):
                self.fields['planta'].queryset = request.user.perfil.plantas.all()
        
    class Meta:
        model = MovimentoVeiculo
        fields = ['planta','entrada','entrada_hora','saida', 'saida_hora', 'motivo', 'placa', 'veiculo', 'cor', 'nota', 'fornecedor',]
        exclude = ['codigo']

class MovimentoVeiculoUpdateForm(MovimentoVeiculoForm):

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            request = kwargs.get('request')
        else:
            request = None
        super(MovimentoVeiculoUpdateForm, self).__init__(*args, **kwargs)

        if not request.user.is_superuser:
            for field in self.fields:
                self.fields[field].widget.attrs['disabled'] = True

onyxlog/portaria/views/index.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from ...core.mixins.core_mixin_login import CoreMixinLoginRequired

class PortariaIndex(CoreMixinLoginRequired, TemplateView):
    template_name = "portaria/portaria_menu.html"

onyxlog/portaria/views/motivo.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Q
from django.shortcuts import redirect
from django.http import Http404

from ...core.base.core_base_datatable import CoreBaseDatatableView
from ...core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from ...core.mixins.core_mixin_login import CoreMixinLoginRequired

from ..models.motivo import Motivo

class MotivoList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista
    """
    template_name = 'portaria/motivo_list.html'
    
class MotivoData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista
    """
    model = Motivo
    columns = ['nome', 'buttons', ]
    order_columns = ['nome',]
    max_display_length = 500
    url_base_form = '/portaria/motivo/'
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(nome__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)

        return qs

class MotivoCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Motivo
    template_name = 'portaria/motivo_form.html'
    success_url = '/'

class MotivoUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = Motivo
    template_name = 'portaria/motivo_form.html'
    success_url = '/'

class MotivoDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = Motivo
    success_url = '/portaria/motivo/'

onyxlog/portaria/views/report.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView

from onyxlog.core.mixins.core_mixin_login import CoreMixinLoginRequired

from ..forms.reportform import ReportForm
from ..models.movimentoveiculo import *
from ..models.movimentovisitante import *

class ReportView(CoreMixinLoginRequired, TemplateView):
    template_name = "portaria/report_form.html"
    form_class = ReportForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return self.render_to_response(self.get_context_data(form=form))
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            self.template_name = "portaria/report_result.html"
            objectResult = self.get_data(request.POST, form)

            filtro_txt = []
            filtro_txt.append('Do dia ' + request.POST['data_inicio'])
            filtro_txt.append(u' até o dia ' + request.POST['data_fim'])

            if request.POST['filtro'] == "1":
                filtro = u"veículos e visitantes"
            elif request.POST['filtro'] == "2":
                filtro = u"apenas veículos"
            else:
                filtro = "apenas visitantes"
            
            filtro_txt.append(', filtrado por ' + filtro)

            if "nota" in request.POST and request.POST["nota"]:
                filtro_txt.append(', referente a nota ' + request.POST["nota"])
            
            if "placa" in request.POST and request.POST["placa"]:
                filtro_txt.append(', referente a placa ' + request.POST["placa"])

            if "cpf" in request.POST and request.POST["cpf"]:
                filtro_txt.append(', referente ao cpf ' + request.POST["cpf"])

            return self.render_to_response(self.get_context_data(object=objectResult, filtro_txt= ''.join(filtro_txt)))
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def get_data(self, data, form):
        result = {
            "veiculos": [],
            "visitantes": [],
        }

        if data["filtro"] in ["1","2"]:
            result["veiculos"] = MovimentoVeiculo.objects.filter(
                entrada__gte= form.cleaned_data["data_inicio"],
                entrada__lte= form.cleaned_data["data_fim"],
            )

            if "nota" in data and data["nota"]:
                result["veiculos"] = result["veiculos"].filter(
                    nota = form.cleaned_data["nota"]
                )

            if "placa" in data and data["placa"]:
                result["veiculos"] = result["veiculos"].filter(
                    placa = form.cleaned_data["placa"]
                )

            if "cpf" in data and data["cpf"]:
                result["veiculos"] = result["veiculos"].filter(
                    ocupantes__cpf=form.cleaned_data["cpf"]
                )

        if data["filtro"] in ["1","3"]:
            result["visitantes"] = MovimentoVisitante.objects.filter(
                entrada__gte= form.cleaned_data["data_inicio"],
                entrada__lte= form.cleaned_data["data_fim"],
            )

            if "nota" in data and data["nota"]:
                result["visitantes"] = result["visitantes"].filter(
                    veiculo__nota= form.cleaned_data["nota"]
                )

            if "placa" in data and data["placa"]:
                result["visitantes"] = result["visitantes"].filter(
                    veiculo__placa= form.cleaned_data["placa"]
                )

            if "cpf" in data and data["cpf"]:
                result["visitantes"] = result["visitantes"].filter(
                    cpf= form.cleaned_data["cpf"]
                )

        return result

onyxlog/portaria/templates/portaria/motivo_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Motivos" "/portaria/motivo/" %}
    
    {% if object %}
        {% breadcrumb form.nome.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}

{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-tag"></i>
    <h3>{% block title %}Motivos de Visita{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'portaria.list_motivo' %}{% endblock %}

onyxlog/portaria/templates/portaria/motivo_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Motivos" "/portaria/motivo/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-tag"></i>
    <h3>{% block title %}Motivos de Visita{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table  table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'portaria.list_json_motivo' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="90%">Nome</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}

onyxlog/portaria/templates/portaria/movimentoveiculo_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap_toolkit %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Movimento de Veículos" "/portaria/movimento/veiculo/" %}
    {% breadcrumb "Nova Entrada" "/portaria/movimento/visitante/formulario" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-truck"></i>
    <h3>{% block title %}Movimento de Veículos{% endblock %}</h3>
{% endblock %}

{% block mainIntra %}
    <div class="div-form">
        {% block formBlock %}
        <form class="form-horizontal" redirect_data="{% url 'portaria.list_movimentoveiculo' %}" method="post" action="{{ request.get_full_path }}" onSubmit="return false;"> 
            {% csrf_token %}
            <div class="row">
                <div class="span6 ">
                    <div class="response_form alert alert-dismissable"><span></span></div>
                </div>
            </div>
            <div class="row">
                <div class="span5">
                    {{ form|as_bootstrap }}
                </div>
                <div class="span6">
                    <fieldset>
                        <legend>Ocupantes do Veículo</legend>
                        <table class="table" id="table-ocupantes">
                            <thead>
                                <tr>
                                    <td width="20%">CPF</td>
                                    <td>Nome</td>
                                    <td width="30%">Empresa</td>
                                    <td width="10%"></td>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                        <button id="btn-add-ocupante" class="btn btn-sm btn-info"><i class="icon-plus"></i> Novo Ocupante</button>
                    </fieldset>
                </div>
            </div>
            
            <div class="form-actions">
            {% block buttonsForm %}
                <button id="btnSend" class="btn btn-primary"><i class="icon-ok"></i> Salvar</button> 
                <button id="btnCancel" class="btn"><i class="icon-arrow-left"></i> Voltar</button>
            {% endblock %}
            </div>
            <span class="ajaxLoading"><img src="{% static 'img/ajax-loader.gif' %}" /></span>

        </form>
        {% endblock %}
    </div>
{% endblock %}

{% block jsExtra %}
    {{ block.super }}
    <script type="text/javascript">var veiculo_id = 0, ocupates_veiculo = [];</script>
    <script type="text/javascript" src="{% static 'js/portaria.veiculo.form.js' %}" ></script>
    <script type="text/javascript">
        form.fnRedirectAfterPost = function(result){
            alert('Entrada do veículo registrada, as etiquetas foram geradas.');
            $('#btnSend').hide();
            window.location.href = "/portaria/movimento/visitante/pdf/";
        };

        $(document).ready(function(){
            $('#id_placa').bind('blur',function(){
                if($('#id_veiculo').val() == ''){
                    $.get(
                        '/portaria/movimento/veiculo/api/'+ $('#id_placa').val() +'/',
                        {},
                        function(response){
                            $('#id_veiculo').val(response.veiculo);
                            $('#id_cor').val(response.cor);
                        }
                    );
                }
            });
        });
    </script>
{% endblock %}

onyxlog/portaria/templates/portaria/movimentoveiculo_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Movimento de Veículos" "/portaria/movimento/veiculo/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-truck"></i>
    <h3>{% block title %}Movimento de Veículos{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table  table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'portaria.list_json_movimentoveiculo' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="5%" >Planta</th>
                <th width="10%" >Entrada</th>
                <th width="5%"  >Hr</th>
                <th width="10%" >Saída</th>
                <th width="5%" class="no_sort">Hr</th>
                <th width="10%" >Código</th>
                <th width="15%" >Veículo</th>
                <th width="7%" >Placa</th>
                <th width="8%" >Nota</th>
                <th width="10%" class="no_sort">Fornecedor</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}

{% block jsExtra %}
    <script type="text/javascript" src="{% static 'core/js/grid.js' %}" ></script>
    <script type="text/javascript">
        $(document).ready(function(){
            grid.fnStartObject({
                'urlData' : "{% url 'portaria.list_json_movimentoveiculo' %}",
                'urlDel'  : '{{ request.get_full_path }}'+'remove/',
                'tableObj': '#gridlist',
                'aaSorting': [[0,'asc'],[1,'desc'], [2,'desc']]
            });
        });
    </script>
    <script type="text/javascript"> $('#btnAddList').bind('click',function(){ window.location.href = 'formulario/' }); </script>
{% endblock %}

onyxlog/portaria/templates/portaria/movimentovisitante_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Movimento de Visitantes" "/portaria/movimento/visitante/" %}
    {% breadcrumb "Nova Entrada" "/portaria/movimento/visitante/formulario" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-user"></i>
    <h3>{% block title %}Movimento de Visitantes{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'portaria.list_movimentovisitante' %}{% endblock %}
{% block jsExtra %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.combobox.js' %}" ></script>
    <script type="text/javascript">
        form.fnRedirectAfterPost = function(result){
            alert('Entrada de visitante registrada, a etiqueta foi gerada.');
            $('#btnSend').hide();
            window.location.href = "/portaria/movimento/visitante/pdf/";
        }

        $(document).ready(function(){
            $('#id_cpf').bind('blur',function(){
                if($('#id_nome').val() == ''){
                    $.get(
                        '/portaria/movimento/visitante/api/'+ $('#id_cpf').val() +'/',
                        {},
                        function(response){
                            $('#id_nome').val(response.nome);
                            $('#id_empresa').val(response.empresa);
                            $('#id_liberado_por').val(response.liberado_por);
                        }
                    );
                }
            });
        });
    </script>
{% endblock %}

onyxlog/portaria/templates/portaria/movimentovisitante_update_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Portaria" "#" %}
    {% breadcrumb "Movimento de Visitantes" "/portaria/movimento/visitante/" %}
    {% breadcrumb "Saída de Visitantes" "/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-user"></i>
    <h3>{% block title %}Movimento de Visitantes{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'portaria.list_movimentovisitante' %}{% endblock %}
{% block buttonsForm %}
    {% if not object.saida %}
    <button id="btnSend" class="btn btn-primary"><i class="icon-signout"></i> Registrar Saída</button> 
    {% endif %}
    <button id="btnCancel" class="btn"><i class="icon-arrow-left"></i> Voltar</button>
{% endblock %}