onyxlog/acesso/urls.py
from django.conf.urls import patterns, include, url

from onyxlog.acesso.views.login import Login, sair
from onyxlog.acesso.views.usuarios import UsuariosList, UsuariosData, UsuariosCreateForm, UsuariosUpdateForm, UsuariosDelete, UsuariosSetPassForm
from onyxlog.acesso.views.grupos import GruposList, GruposData, GruposCreateForm, GruposUpdateForm, GruposDelete
from onyxlog.acesso.views.permissoes import PermissoesList, PermissoesData, PermissoesCreateForm, PermissoesUpdateForm, PermissoesDelete

urlpatterns = patterns('',
    url(r'^auth/', Login.as_view()),

    #Usuarios
    url(r'^usuarios/data/$', UsuariosData.as_view(),name='acesso.list_json_usuario'),
    url(r'^usuarios/formulario/$', UsuariosCreateForm.as_view(),name='acesso.add_usuario'),
    url(r'^usuarios/(?P<pk>\d+)/$', UsuariosUpdateForm.as_view(),name='acesso.change_usuario'),
    url(r'^usuarios/password/$', UsuariosSetPassForm.as_view(),name='acesso.change_pass_usuario'),
    url(r'^usuarios/remove/(?P<pk>\d+)/$', UsuariosDelete.as_view(),name='acesso.delete_usuario'),
    url(r'^usuarios/$', UsuariosList.as_view(), name='acesso.list_usuario'),

    #Grupos
    url(r'^grupos/data/$', GruposData.as_view(),name='auth.list_json_group'),
    url(r'^grupos/formulario/$', GruposCreateForm.as_view(),name='auth.add_group'),
    url(r'^grupos/(?P<pk>\d+)/$', GruposUpdateForm.as_view(),name='auth.change_group'),
    url(r'^grupos/remove/(?P<pk>\d+)/$', GruposDelete.as_view(),name='auth.delete_group'),
    url(r'^grupos/$', GruposList.as_view(), name='auth.list_group'),

    #Permissoes
    url(r'^permissoes/data/$', PermissoesData.as_view(),name='auth.list_json_permission'),
    url(r'^permissoes/formulario/$', PermissoesCreateForm.as_view(),name='auth.add_permission'),
    url(r'^permissoes/(?P<pk>\d+)/$', PermissoesUpdateForm.as_view(),name='auth.change_permission'),
    url(r'^permissoes/remove/(?P<pk>\d+)/$', PermissoesDelete.as_view(),name='auth.delete_permission'),
    url(r'^permissoes/$', PermissoesList.as_view(), name='auth.list_permission'),
    
    url(r'^sair/', sair, name='sair'),
)

onyxlog/urls.py
from django.views.generic import RedirectView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('onyxlog.core.urls'),name="App-Principal"),

    url(r'^core/', include('onyxlog.core.urls')),
    url(r'^acesso/', include('onyxlog.acesso.urls')),
    url(r'^cadastros/', include('onyxlog.cadastros.urls')),
    url(r'^etiquetas/', include('onyxlog.etiqueta.urls')),
    url(r'^estoque/', include('onyxlog.estoque.urls')),
    url(r'^portaria/', include('onyxlog.portaria.urls')),
    # Examples:
    # url(r'^$', 'onyxlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

handler403 = 'onyxlog.core.views.core.error403'
handler404 = 'onyxlog.core.views.core.error404'
handler500 = 'onyxlog.core.views.core.error500'

onyxlog/acesso/models/perfil.py
# -*- coding: utf-8 -*-
from django.db import models

class Perfil(models.Model):
    user = models.OneToOneField('auth.User', null=False)
    plantas = models.ManyToManyField(
            'cadastros.Planta',
            verbose_name='Platas de Operação',
            blank=False,
            null=True,
            related_name='perfil',
        )

    class Meta:
        app_label = 'acesso'

onyxlog/acesso/forms/grupoform.py
# -*- coding: ISO-8859-1 -*-
from django import forms
from django.contrib.auth.models import Group

class GrupoCreateForm(forms.ModelForm):
    """
    Formulário de Grupos
    """
    
    class Meta:
        model = Group
        exclude = ('permissions',)

    def get_absolute_url(self):
        return reverse('acesso.list_group', kwargs={'pk': self.pk})

onyxlog/acesso/forms/loginform.py
# -*- coding: ISO-8859-1 -*-
from django import forms

class LoginForm(forms.Form):
    """
    Formulário de Login da aplicação
    """
    username = forms.CharField(
        label='', 
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Usuário',
            }
        ), 
        error_messages={
            'required': 'Este campo é obrigatório',
        }
    )
    senha = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'Senha',
            }
        ), 
        error_messages={
            'required': 'Este campo é obrigatório',
        }
    )

onyxlog/acesso/forms/usuarioform.py
# -*- coding: ISO-8859-1 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.hashers import make_password

from django.contrib.auth.models import User

from ...cadastros.models import Planta

class UsuarioCreateForm(UserCreationForm):
    """
    Formulário de usuários
    """
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    
    class Meta:
        model = User
        exclude = ('last_login','is_staff','date_joined','is_superuser', 'password', 'groups','user_permissions', )

    def __init__(self, *args, **kwargs):
        super(UsuarioCreateForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'is_active', 
            'password1', 
            'password2', 
        ]

    def get_absolute_url(self):
        return reverse('acesso.list_usuario', kwargs={'pk': self.pk})

class UsuarioUpdateForm(UserChangeForm):
    """
    Formulário de usuários
    """
    username = forms.CharField(required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    plantas = forms.MultipleChoiceField(
        label="Plantas de Operação",
        help_text='Plantas de operação que o usuário tem acesso. Mantenha o "Control", \
        ou "Command" no Mac, pressionado para selecionar mais de uma opção.',
        required=False,
        choices=((item.id, item.nome) for item in Planta.objects.all())
    )
    m2mSave  = False
    
    class Meta:
        model = User
        exclude = ('last_login','is_staff','date_joined','is_superuser',)

    def __init__(self, *args, **kwargs):
        super(UsuarioUpdateForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'username', 'first_name', 'last_name', 'password', 'email', 
            'telefone', 'is_active', 'groups', 'plantas', 'user_permissions',
        ]

    def clean_password(self):
        """
        Permite alteração da senha no formulário de usuários
        """
        if len(self.cleaned_data.get('password')):
            return make_password(self.cleaned_data.get('password'))
        else:
            return self.initial["password"]

    def save(self, commit=True):
        instance = super(UsuarioUpdateForm,self).save(commit=False)
        old_save_m2m = self.save_m2m #guarda antiga função para campos manytomany

        def save_m2m():
            if not self.m2mSave:
                #old_save_m2m()
                instance.user_permissions.clear()
                instance.groups.clear()

                for permission in self.cleaned_data['user_permissions']:
                    instance.user_permissions.add(permission)

                for group in self.cleaned_data['groups']:
                    instance.groups.add(group)

                #self.m2mSave = True
        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance

onyxlog/acesso/views/grupos.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Q
from django.contrib.auth.models import Group
from django.shortcuts import redirect

from onyxlog.core.base.core_base_datatable import CoreBaseDatatableView
from onyxlog.core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from onyxlog.core.mixins.core_mixin_login import CoreMixinLoginRequired

from onyxlog.acesso.forms.grupoform import GrupoCreateForm

class GruposList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista de grupos
    """
    template_name = 'grupo_list.html'
    
class GruposData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista de grupos
    """
    model = Group
    columns = ['id','name', 'buttons']
    order_columns = ['id','name']
    max_display_length = 500
    url_base_form = '/acesso/grupos/'
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(name__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)
        return qs

class GruposCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação de grupos
    """
    model = Group
    template_name = 'grupo_form.html'
    success_url = '/'
    form_class = GrupoCreateForm

class GruposUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação de grupos
    """
    model = Group
    template_name = 'grupo_form.html'
    success_url = '/'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        permissions = request.POST.getlist('permissions[]')

        if form.is_valid():
            form.cleaned_data['permissions'] = permissions
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    #Retorno caso o formulário seja válido
    def form_valid(self, form):
        permissions = form.cleaned_data['permissions']
        self.object = form.save()
        self.object.permissions.clear()

        for permission in permissions:
            self.object.permissions.add(permission)
        
        self.object.save()        
        return self.render_to_json_reponse({'success': True, 'message': 'Registro incluido com sucesso.'},status=200)

class GruposDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = Group
    success_url = '/acesso/grupos/'

onyxlog/acesso/views/login.py
# -*- coding: ISO-8859-1 -*-
import json
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout

from onyxlog.acesso.forms.loginform import LoginForm

class Login(FormView):
    """
    View de login para validar autenticação de Usuário
    """
    
    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('/')
        else:
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            nextUrl = '/'
            if 'next' in request.GET.keys():
                nextUrl = request.GET['next']

            return self.render_to_response(self.get_context_data(form=form,urlRedirect=nextUrl))

    #Renderiza em json a resposta
    def render_to_json_reponse(self, context, **response_kwargs):
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    #Retorno para invalidez do formulário
    def form_invalid(self, form):
        response = super(Login, self).form_invalid(form)
        if self.request.is_ajax():
            return self.render_to_json_reponse(form.errors, status=400)
        else:
            return response
        
    #Retorno caso o formulário seja válido
    def form_valid(self, form):
        response = super(Login, self).form_valid(form)

        userAuth = authenticate(username=self.request.POST['username'], password=self.request.POST['senha'])
        if not userAuth is None:
            if userAuth.is_active: #Usuário ativo
                login(self.request,userAuth)
                if self.request.is_ajax():
                    return self.render_to_json_reponse({'urlRedirect':'/'},status=200)
                else:
                    return redirect('/')
            else:
                return self.render_to_json_reponse({'username':['Usuário desativado']},status=400)
        elif self.request.is_ajax():
            return self.render_to_json_reponse({'csrfmiddlewaretoken':'Usuário ou senha inválido'},status=400)
        else:
            return HttpResponse(u'Usuário ou senha inválido',status=400)

def sair(request):
    """
    View para saída do sistema
    """
    logout(request)
    return redirect('/acesso/auth/')

onyxlog/acesso/views/permissoes.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Q
from django.contrib.auth.models import Permission
from django.shortcuts import redirect

from onyxlog.core.base.core_base_datatable import CoreBaseDatatableView
from onyxlog.core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from onyxlog.core.mixins.core_mixin_login import CoreMixinLoginRequired

class PermissoesList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista de permissões
    """
    template_name = 'permissao_list.html'
    
class PermissoesData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista de permissões
    """
    model = Permission
    columns = ['id','name', 'codename', 'buttons']
    order_columns = ['id','name']
    max_display_length = 500
    url_base_form = '/acesso/permissoes/'
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(name__istartswith=part)|Q(codename__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)
        return qs

class PermissoesCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação de permissões
    """
    model = Permission
    template_name = 'permissao_form.html'
    success_url = '/'

class PermissoesUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação de permissões
    """
    model = Permission
    template_name = 'permissao_form.html'
    success_url = '/'

class PermissoesDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = Permission
    success_url = '/acesso/permissoes/'

onyxlog/cadastros/views/grupo.py
# -*- coding: ISO-8859-1 -*-
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Q
from django.shortcuts import redirect
from django.http import Http404

from onyxlog.core.base.core_base_datatable import CoreBaseDatatableView
from onyxlog.core.mixins.core_mixin_form import CoreMixinForm, CoreMixinDel
from onyxlog.core.mixins.core_mixin_login import CoreMixinLoginRequired

from ..models.grupo import GrupoProduto

class GrupoProdutoList(CoreMixinLoginRequired, TemplateView):
    """
    View para renderização da lista
    """
    template_name = 'grupoproduto_list.html'
    
class GrupoProdutoData(CoreMixinLoginRequired, CoreBaseDatatableView):
    """
    View para renderização da lista
    """
    model = GrupoProduto
    columns = ['nome', 'buttons', ]
    order_columns = ['nome',]
    max_display_length = 500
    url_base_form = '/cadastros/grupo-produto/'
    
    def filter_queryset(self, qs):
        """
        Filtros da query baseado no datatable
        """
        sSearch = self.request.GET.get('sSearch', None)
        if sSearch:
            search_parts = sSearch.split('+')
            qs_params = None
            for part in search_parts:
                q = Q(nome__istartswith=part)
                qs_params = qs_params | q if qs_params else q

            qs = qs.filter(qs_params)

        return qs

class GrupoProdutoCreateForm(CoreMixinLoginRequired, CreateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = GrupoProduto
    template_name = 'grupoproduto_form.html'
    success_url = '/'

class GrupoProdutoUpdateForm(CoreMixinLoginRequired, UpdateView, CoreMixinForm):
    """
    Formulário de criação
    """
    model = GrupoProduto
    template_name = 'grupoproduto_form.html'
    success_url = '/'

class GrupoProdutoDelete(CoreMixinLoginRequired, CoreMixinDel):
    """
    View de exclusão de itens
    """
    model = GrupoProduto
    success_url = '/cadastros/grupo-produto/'

onyxlog/acesso/templates/grupo_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Configurações" "#" %}
    {% breadcrumb "Grupos" "/acesso/grupos/" %}
    
    {% if object %}
        {% breadcrumb form.first_name.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}

{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-group"></i>
    <h3>{% block title %}Grupos de Usuários{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'auth.list_group' %}{% endblock %}

onyxlog/acesso/templates/grupo_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Configurações" "#" %}
    {% breadcrumb "Grupos" "/acesso/grupos/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-group"></i>
    <h3>{% block title %}Grupo de Usuários{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'auth.list_json_group' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="10%">Código</th>
                <th width="75%">Grupo</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}

onyxlog/acesso/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">  
<head>
    <meta charset="utf-8">
    <title>Login - OnyxLoc</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes"> 
    <meta name="author" content="Jair Verçosa - onyxti.com.br" />
    
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'core/css/bootstrap-responsive.min.css' %}" rel="stylesheet" type="text/css" />

    <link href="{% static 'core/css/font-awesome.css' %}" rel="stylesheet">
    <!--<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">-->
    
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/pages/signin.css' %}" rel="stylesheet" type="text/css">

    <style type="text/css">
        @font-face {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 300;
            src: local('Open Sans Light'), local('OpenSans-Light'), url(http://themes.googleusercontent.com/fonts/opensans/v6/DXI1ORHCpsQm3Vp6mXoaTaRDOzjiPcYnFooOUGCOsRk.woff) format('woff');
        }
    </style>

</head>

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="index.html">
                    <img src="{% static 'img/logo-black.png' %}" height="40" />
                </a>        
            </div> <!-- /container -->
        </div> <!-- /navbar-inner -->
    </div> <!-- /navbar -->

    <div class="account-container"> 
        <div class="content clearfix">
            <form method="post" action="/acesso/auth/" id="formLogin" onSubmit="return false;">
                {% csrf_token %}
                <h1>Login</h1>      
                <div class="login-fields">
                    <p>Entre com seu usuário e senha</p>
                    <div class="field">
                        <label for="username">Usuário</label>
                        <input class="form-control login username-field" id="id_username" name="username" placeholder="Usuário" type="text" />
                        {{ form.username.errors }}
                    </div> <!-- /field -->
                    <div class="field">
                        <label for="password">Senha</label>
                        <input class="form-control login password-field" id="id_senha" name="senha" placeholder="Senha" type="password" />
                        {{ form.senha.errors }}
                    </div> <!-- /password -->               
                </div> <!-- /login-fields -->
                <div class="login-actions">
                    <button type="submit" class="button btn btn-success btn-large" id="btnSend">Entrar</button>
                </div> <!-- .actions -->
                <span class="ajaxLoading"><img src="{% static 'img/ajax-loader.gif' %}" /></span>
            </form>
        </div> <!-- /content -->
    </div> <!-- /account-container -->

    <!--<div class="login-extra">
        <a href="#">Esqueci minha senha</a>
    </div>--> <!-- /login-extra -->


    <script src="{% static 'core/js/jquery-1.7.2.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.js' %}"></script>
    <script src="{% static 'js/app.js' %}" ></script>
    <script type="text/javascript">
            $('#btnSend').bind('click',function(){
                var obj;
                app.addLoading(obj,true);
                $('.error-div-form').remove();
                $.ajax({
                    type: 'post',
                    url: $('#formLogin').attr('action'),
                    data: {
                        'csrfmiddlewaretoken' : $('input[name=csrfmiddlewaretoken]').val(),
                        'username' : $('input[name=username]').val(),
                        'senha' : $('input[name=senha]').val()
                    },
                    success: function(response){
                        app.removeLoading();
                        try{
                            var redirect = '';
                            result = $.parseJSON(response.responseText);
                            if($('#urlRedirect').val() == '')
                                redirect = result.urlRedirect;
                            else
                                redirect = $('#urlRedirect').val();

                            window.location.href = redirect;
                        }catch(err){
                            console.log(err.message+'\n\n'+response);
                            alert(err.message);
                        }
                    },
                    error: function(response){
                        app.removeLoading();
                        try{
                            var result = $.parseJSON(response.responseText);
                            if(typeof result.username != 'undefined'){
                                if(result.username.length > 0){
                                    $("input[name=username]").after('<div class="error-div-form"><small>'+result.username[0]+'</small></div>');
                                }
                            }

                            if(typeof result.senha != 'undefined'){
                                if(result.senha.length > 0){
                                    $("input[name=senha]").after('<div class="error-div-form"><small>'+result.senha[0]+'</small></div>');
                                }
                            }

                            if(typeof result.csrfmiddlewaretoken != 'undefined'){
                                $("input[name=csrfmiddlewaretoken]").after('<div class="error-div-form"><small>'+result.csrfmiddlewaretoken+'</small></div>');
                            }
                        }catch(err){
                            console.log(err.message+'\n\n'+response.responseText);
                            alert('Ocorreu uma falha na operação');
                        }
                    }
                });
                return false;
            });
        </script>

</body>

</html>

onyxlog/acesso/templates/permissao_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Configurações" "#" %}
    {% breadcrumb "Permissões" "/acesso/permissoes/" %}
    
    {% if object %}
        {% breadcrumb form.name.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}

{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="iicon-unlock"></i>
    <h3>{% block title %}Permissões{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'auth.list_permission' %}{% endblock %}

onyxlog/acesso/templates/permissao_list.html
{% extends 'core/base_list.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Configurações" "#" %}
    {% breadcrumb "Permissões" "/acesso/permissoes/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-unlock"></i>
    <h3>{% block title %}Permissões{% endblock %}</h3>
    <button id="btnAddList" class="btn btn-sm btn-success"><i class="no-margin-left icon-plus"></i> Novo</button>
{% endblock %}

{% block tableList %}
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-hover datatable" id="gridlist" url-data-source="{% url 'auth.list_json_permission' %}">
        {% csrf_token %}
        <thead>
            <tr>
                <th width="10%">Código</th>
                <th width="55%">Nome</th>
                <th width="20%">Apelido</th>
                <th width="10%" class="no_sort"></th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot></tfoot>
    </table>
{% endblock %}

onyxlog/acesso/templates/usuario_form.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Configurações" "#" %}
    {% breadcrumb "Usuários" "/acesso/usuarios/" %}
    
    {% if object %}
        {% breadcrumb form.first_name.value|add:' ' "/" %}
    {% else %}
        {% breadcrumb "Novo" "" %}
    {% endif %}

{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-user"></i>
    <h3>{% block title %}Usuários{% endblock %}</h3>
{% endblock %}

{% block redirectForm%}{% url 'acesso.list_usuario' %}{% endblock %}

onyxlog/acesso/templates/usuario_form_change_pass.html
{% extends "base_form.html"%}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap_toolkit %}

{% block title %}Trocar Senha{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Configurações" "/core/configuracoes/" %}
    {% breadcrumb "Usuários" "/acesso/usuarios/" %}
    {% breadcrumb userUpdate.first_name|add:' '|add:userUpdate.last_name "/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}


{% block formRender %}
    <div class="row">
        <div class="col-lg-6 ">
            <div class="response_form alert alert-dismissable"><span></span></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 top-buffer-10">
            <form class="form-horizontal" redirect_data="{% url 'core_index' %}" method="post" action="{{ request.get_full_path }}" id="formUsuarios" onSubmit="return false;">
                <input type="hidden" name="pk" value="{{ userUpdate.id }}" />
                {% csrf_token %}
                {{ form|as_bootstrap }}
                {% block button %}
                    {{ block.super }}
                {% endblock %}
            </form>
        </div>
    </div>
{% endblock %}