onyxlog/etiqueta/urls.py
from django.conf.urls import patterns, include, url

from views.etiqueta import EtiquetaIndex, EtiquetaProduto, EtiquetaEndereco

urlpatterns = patterns('',
    url(r'^$', EtiquetaIndex.as_view(), name='etiqueta.etiqueta_index'),
    
    url(r'^produto/pdf/', 'onyxlog.etiqueta.views.etiqueta.pdfEtiquetaProduto', name='etiqueta.etiqueta_produto_pdf'),
    url(r'^produto/', EtiquetaProduto.as_view(), name='etiqueta.etiqueta_produto'),

    url(r'^endereco/pdf/', 'onyxlog.etiqueta.views.etiqueta.pdfEtiquetaEndereco', name='etiqueta.etiqueta_endereco_pdf'),
    url(r'^endereco/', EtiquetaEndereco.as_view(), name='etiqueta.etiqueta_endereco'),
    
)

onyxlog/urls.py
from django.views.generic import RedirectView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('onyxlog.core.urls'),name="App-Principal"),

    url(r'^core/', include('onyxlog.core.urls')),
    url(r'^acesso/', include('onyxlog.acesso.urls')),
    url(r'^cadastros/', include('onyxlog.cadastros.urls')),
    url(r'^etiquetas/', include('onyxlog.etiqueta.urls')),
    url(r'^estoque/', include('onyxlog.estoque.urls')),
    url(r'^portaria/', include('onyxlog.portaria.urls')),
    # Examples:
    # url(r'^$', 'onyxlog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

handler403 = 'onyxlog.core.views.core.error403'
handler404 = 'onyxlog.core.views.core.error404'
handler500 = 'onyxlog.core.views.core.error500'

onyxlog/etiqueta/forms/etiquetaestoqueform.py
# -*- coding: ISO-8859-1 -*-
from django import forms
from django.forms.widgets import *
from ...estoque.models.endereco import Endereco

class EtiquetaEnderecoForm(forms.Form):
    codigo_de = forms.ModelChoiceField(
        queryset=Endereco.objects.all(),
        label="Do Endereço",
        required=True,
    )
    
    codigo_ate = forms.ModelChoiceField(
        queryset=Endereco.objects.all(),
        label="Até o Endereço",
        required=True,
    )

    def get_absolute_url(self):
        return reverse('etiqueta.etiqueta_endereco')

onyxlog/etiqueta/forms/etiquetaprodutoform.py
# -*- coding: ISO-8859-1 -*-
from django import forms
from django.forms.widgets import *
from ...cadastros.models.produto import Produto
from ...estoque.models.endereco import Endereco

class EtiquetaProdutoForm(forms.Form):
    produto = forms.ModelChoiceField(
        queryset=Produto.objects.all(),
        label="Produto",
        help_text="Produto que será usado na etiqueta.",
        required=True,
    )
    
    qtd = forms.FloatField(
        label="Qtd",
        help_text="Quantidade do produto",
        required=False,
    )

    validade = forms.DateField(
        label="Validade",
        help_text="Validade do produto",
        required=False,
    )

    endereco = forms.ModelChoiceField(
        queryset=Endereco.objects.all(),
        label="Endereço",
        help_text="Endereço do produto",
        required=False,
    )

    nota = forms.CharField(
        label="Nota Fiscal",
        help_text="Nota fiscal em que o produto foi recebido",
        max_length=10,
        required=False,
    )

    pedido = forms.CharField(
        label="Pedido",
        max_length=10,
        required=False,
    )
    
    dtRecebimento = forms.DateField(
        label="Recebido em",
        help_text="Data do recebimento do produto que será impresso na etiqueta",
        required=False,
    )

    fornecedor = forms.CharField(
        label="Fornecedor do Produto",
        help_text="Nome do fornecedor que será impresso na etiqueta. \
                   Caso não seja preenchido será considerado o fornecedor preenchido \
                   no cadastro de produtos",
        max_length=120,
        required=False,
    )

onyxlog/etiqueta/views/etiqueta.py
# -*- coding: ISO-8859-1 -*-
import os
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.graphics.barcode import code128
from reportlab.lib.units import mm

from django.http import HttpResponse
from django.views.generic import TemplateView
from django.db.models import Q
from django.conf import settings
from django.shortcuts import redirect

from ...core.mixins.core_mixin_login import CoreMixinLoginRequired
from ...core.mixins.core_mixin_base import CoreMixinDispatch
from ...core.mixins.core_mixin_form import CoreMixin, CoreMixinForm

from ..forms.etiquetaestoqueform import EtiquetaEnderecoForm
from ..forms.etiquetaprodutoform import EtiquetaProdutoForm
from ...cadastros.models.produto import Produto
from ...estoque.models.endereco import Endereco

class EtiquetaIndex(CoreMixinLoginRequired, TemplateView):
    template_name = "etiqueta_menu.html"

class EtiquetaProduto(CoreMixinLoginRequired, TemplateView, CoreMixin):
    template_name = "etiqueta_list_produto.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)
        
    def post(self, request, *args, **kwargs):
        dataPost = eval(request.POST.getlist('data')[0])
        dataToLabel = []

        # valida os dados digitados com o formulário
        for item in dataPost:
            dataForm = {
                "produto"       : item['id'],
                "qtd"           : item['qtd'],
                "endereco"      : item['endereco'],
                "validade"      : item['validade'],
                "nota"          : item['nota'],
                "pedido"        : item['pedido'],
                "dtRecebimento" : item['dtRecebimento'],
                "fornecedor"    : item['fornecedor'],
            }
            form = EtiquetaProdutoForm(dataForm)

            if not form.is_valid():
                return self.render_to_json_reponse(form.errors, status=400)
            else:
                dataToLabel.append(dataForm)
        
        # prepara dados para etiqueta
        data = []
        for posted in dataToLabel:
            produto = Produto.objects.get(pk=posted['produto'])
            if posted['endereco']:
                endereco = Endereco.objects.get(pk=posted['endereco']).codigo
            else:
                endereco = ''

            if produto.validade and not posted['validade']:
                return self.render_to_json_reponse(context={
                        'success':False, 
                        'message': 'Existem produtos que controlam validade e que a mesma não foi preenchida.'
                    },status=400)

            data.append({
                "codigo": produto.codigo,
                "descricao": produto.desc,
                "qtd": posted['qtd'],
                "endereco": endereco,
                "validade": posted['validade'],
                "nota": posted['nota'],
                "pedido": posted['pedido'],
                "un": produto.unidade.nome,
                "grupo": produto.grupo.nome,
                "recebimento": posted['dtRecebimento'],
                "fornecedor": posted['fornecedor'],
            })

    
        if data:
            request.session['dataEtiqueta'] = data
            return self.render_to_json_reponse(context={
                'success':True, 
                'message': 'Etiquetas geradas com sucesso.',
            },status=200)
        else:
            return self.render_to_json_reponse(context={
                'success':False, 
                'message': 'Nenhum produto foi encontrado.'
            },status=400)

def pdfEtiquetaProduto(request):
    """
    Gera arquivo PDF das etiquetas solicitadas
    """

    if 'dataEtiqueta' not in request.session:
        redirect('etiqueta.etiqueta_produto')
    
    data = request.session['dataEtiqueta']
    if not data:
        redirect('etiqueta.etiqueta_produto')
        
    request.session.pop('dataEtiqueta')

    if settings.DEBUG:
        logo_company = settings.BASE_DIR+'/onyxlog/core/static/img/logo_company_label.jpg'
        logo_company2 = settings.BASE_DIR+'/onyxlog/core/static/img/logo_company_label2.jpg'
    else:
        logo_company = settings.STATIC_ROOT+'/img/logo_company_label.jpg'
        logo_company2 = settings.STATIC_ROOT+'/img/logo_company_label2.jpg'

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="etiquetas_produto.pdf"'

    buffer = BytesIO()

    p = canvas.Canvas(buffer, pagesize=(378,264))
    
    for produto in data:
        # cabeçalho
        p.drawImage(logo_company,5,228,)
        p.drawImage(logo_company2,292,228,)
        p.drawString(122, 239, "Etiqueta de Identificação.")

        # label dos detalhes
        p.setFontSize(7)
        p.rect(5,191,365,31,fill=0)
        p.drawString(7,214, "Produto")

        p.rect(5,160,80,31,fill=0)
        p.drawString(7,183, "UN")

        p.rect(85,160,90,31,fill=0)
        p.drawString(88,183, "Qtd")

        p.rect(175,160,90,31,fill=0)
        p.drawString(178,183, "Nota")

        p.rect(265,160,105,31,fill=0)
        p.drawString(268,183, "Pedido")

        p.rect(5,129,365,31,fill=0)
        p.drawString(7,152, "Fornecedor")

        p.rect(265,129,105,31,fill=0)
        p.drawString(268,152, "Validade")

        # box do codigo de barras
        p.rect(5,10,220,119,fill=0)
        
        p.rect(225,72,145,57,fill=0)
        p.drawString(227,121, "Código do Produto")
        p.rect(225,75,145,40,fill=1)

        p.rect(225,41,145,31,fill=0)
        p.drawString(227,65, "Endereço")

        p.rect(225,10,145,31,fill=0)
        p.drawString(227,34, "Recebimento")


        # imprime os dados
        p.setFontSize(10)
        p.drawString(7,200, produto['descricao'])

        p.setFontSize(16)
        p.drawString(17 ,167, produto['un'])
        p.drawString(88 ,167, produto['qtd'])
        p.drawString(178,167, produto['nota'])
        p.drawString(268,167, produto['pedido'])
        p.drawString(17 ,136, produto['fornecedor'])
        p.drawString(268,136, produto['validade'])
        p.drawString(242,19 , produto['recebimento'])

        # codigo de barras
        barcode = code128.Code128(produto['codigo'],barWidth=0.5*mm,barHeight=30*mm)
        barcode.drawOn(p,5,35)
        p.setFontSize(10)
        p.drawCentredString(120,15, produto['codigo'])

        p.setFontSize(16)
        p.setFillColorRGB(255,255,255)
        p.drawString(230,90, produto['codigo'])

        p.setFontSize(14)
        p.setFillColorRGB(0,0,0)
        p.drawString(230,50, produto['endereco'])
        p.showPage()

    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

class EtiquetaEndereco(CoreMixinLoginRequired, TemplateView, CoreMixinForm):
    template_name = "etiqueta_endereco.html"
    success_url = '/'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['form'] =  EtiquetaEnderecoForm()
        return self.render_to_response(context)
        
    def post(self, request, *args, **kwargs):
        form = EtiquetaEnderecoForm(request.POST)

        if not form.is_valid():
            return self.form_invalid(form)
        else:
            dataEnderecos = []
            enderecos = Endereco.objects.filter(
                codigo__gte=Endereco.objects.get(pk=form.data['codigo_de']).codigo,
                codigo__lte=Endereco.objects.get(pk=form.data['codigo_ate']).codigo,
            )
            
            for item in enderecos:
                dataEnderecos.append({
                    "codigo": item.codigo,
                    "planta": item.planta.nome if item.planta else '',
                })

            request.session['dataEtiquetaEndereco'] = dataEnderecos
            return self.form_valid(form)

    def form_valid(self, form):
        response = super(EtiquetaEndereco, self).form_valid(form)
        return self.render_to_json_reponse(context={'success':True, 'message': 'Etiquetas geradas com sucesso.'},status=200)
         

def pdfEtiquetaEndereco(request):
    """
    Gera arquivo PDF das etiquetas solicitadas
    """

    if 'dataEtiquetaEndereco' not in request.session:
        redirect('etiqueta.etiqueta_endereco')
    
    data = request.session['dataEtiquetaEndereco']
    if not data:
        redirect('etiqueta.etiqueta_endereco')
    
    request.session.pop('dataEtiquetaEndereco')


    if settings.DEBUG:
        logo_company = settings.BASE_DIR+'/onyxlog/core/static/img/logo_company_label.jpg'
        logo_company2 = settings.BASE_DIR+'/onyxlog/core/static/img/logo_company_label2.jpg'
    else:
        logo_company = settings.STATIC_ROOT+'/img/logo_company_label.jpg'
        logo_company2 = settings.STATIC_ROOT+'/img/logo_company_label2.jpg'

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="etiqueta_endereco.pdf"'

    buffer = BytesIO()

    p = canvas.Canvas(buffer, pagesize=(378,264))

    for endereco in data:
        # cabeçalho
        p.drawImage(logo_company,5,228,)
        p.drawImage(logo_company2,292,228,)
        p.drawCentredString(193, 249, "Etiqueta de Identificação.")
        p.drawCentredString(193, 231, "de Endereço.")

        # label dos detalhes
        p.setFontSize(7)
        p.rect(5,191,365,31,fill=0)
        p.drawString(12,214, "Planta")

        p.rect(5,129,365,62,fill=0)
        p.drawString(12,183, "Endereço")

        # box do codigo de barras
        p.rect(5,10,365,119,fill=0)
        
        # imprime os dados
        p.setFontSize(16)
        p.drawString(17,198, endereco['planta'])

        p.setFontSize(22)
        p.drawCentredString(188,151, endereco['codigo'])
        
        # codigo de barras
        barcode = code128.Code128(endereco['codigo'],barWidth=0.5*mm,barHeight=30*mm)
        barcode.drawOn(p,50,35)

onyxlog/etiqueta/templates/etiqueta_endereco.html
{% extends 'core/base_form.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap_toolkit %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Etiquetas" "#" %}
    {% breadcrumb "Endereço" "/etiquetas/endereco/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block titleIntra %}
    <i class="icon-bookmark"></i>
    <h3>{% block title %}Etiqueta de Endereços{% endblock %}</h3>
{% endblock %}

{% block mainIntra %}
    <div class="div-form">
        {% block formBlock %}
        <form class="form-horizontal" redirect_data="{% url 'etiqueta.etiqueta_index' %}" method="post" action="{{ request.get_full_path }}" onSubmit="return false;"> 
            {% csrf_token %}
            <div class="row">
                <div class="span6 ">
                    <div class="response_form alert alert-dismissable"><span></span></div>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    {{ form|as_bootstrap }}
                </div>
            </div>
            
            <div class="form-actions">
            {% block buttonsForm %}
                <button id="btnSend" class="btn btn-primary"><i class="icon-print"></i> Gerar Etiquetas</button> 
            {% endblock %}
            </div>
            <span class="ajaxLoading"><img src="{% static 'img/ajax-loader.gif' %}" /></span>

        </form>
        {% endblock %}
    </div>
{% endblock %}

{% block jsExtra %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.combobox.js' %}" ></script>
    <script type="text/javascript">
        $(document).ready(function(){
            form.fnRedirectAfterPost = function(result){
                window.location.href = "{% url 'etiqueta.etiqueta_endereco_pdf' %}";
            }

            $('#id_codigo_de, #id_codigo_ate').combobox();
        });
    </script>
{% endblock %}

onyxlog/etiqueta/templates/etiqueta_itens_menu.html
<li><a href="{% url 'etiqueta.etiqueta_produto' %}">Identificação de Produtos</a></li>
<li><a href="{% url 'etiqueta.etiqueta_endereco' %}">Identificação de Endereços</a></li>

onyxlog/etiqueta/templates/etiqueta_list_produto.html
{% extends 'core/base_intra.html' %}
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% load bootstrap_toolkit %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Início" "/" %}
    {% breadcrumb "Etiquetas" "#" %}
    {% breadcrumb "Produto" "/etiquetas/produto/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block extraStyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'libs/datatables/css/jquery.datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libs/plugins/css/jquery-ui-1.10.4.custom.min.css' %}">
{% endblock %}

{% block titleIntra %}
    <i class="icon-shopping-cart"></i>
    <h3>{% block title %}Etiqueta de Produtos{% endblock %}</h3> 
{% endblock %}

{% block mainIntra %}
    <div ng-app="etiquetasApp" ng-controller="controllerProduto">
        <div class="row" >
            <div class="span12">
                <div>
                    <p><i class="icon-info-sign"></i> Utilize o botão adicionar para aumentar a lista de produtos para impressão.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="span6">
                <div class="response_form alert alert-dismissable"><span></span></div>
            </div>
        </div>
        <div class="row">
            <form class="form-vertical" method="" action="{{ request.get_full_path }}" id="formEtiquetaProduto" onSubmit="return false;">
                {% csrf_token %}
                <div class="span6">
                    <div class="control-group custom-produto">
                        <label class="control-label" for="id_produto_id">Produto</label>
                        <div><small>Selecione o produto desejado e clique em adicionar.</small></div>
                        <div class="controls">
                            <select id="id_produto_id" name="produto"></select>
                        </div>
                        <button type="submit" class="btn btn-sm btn-success" id="btnSend" ng-click="addProduct()">
                            <i class="icon-plus"></i> Adicionar
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="span11">
                <div class="well box-white">
                    <table cellpadding="0" cellspacing="0" border="0" class="table  table-striped table-hover" id="table-print-label">
                        {% csrf_token %}
                        <thead>
                            <tr>
                                <th width="5%">Código</th>
                                <th width="15%">Produto</th>
                                <th width="5%">UN</th>
                                <th width="10%">Qtd</th>
                                <th width="10%">Endereço</th>
                                <th width="10%">Validade</th>
                                <th width="10%">Nota</th>
                                <th width="10%">Pedido</th>
                                <th width="10%">Fornecedor</th>
                                <th width="10%">Recebimento</th>
                                <th width="5%" class="no_sort"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="x in products">
                                <td>{$ x.codigo $}</td>
                                <td>{$ x.desc $}</td>
                                <td>{$ x.un $}</td>
                                <td><input class="form-control" name="qtd" value="{$ x.qtd $}"/></td>
                                <td>
                                    <select class="form-control" name="endereco">
                                        <option value=""></option>
                                        <option ng-repeat="y in adress" value="{$ y.id $}">{$ y.codigo $}</option>
                                    </select>
                                </td>
                                <td><input ng-class="{'border-red': x.validadeRequired}" class="form-control" name="validade" value="{$ x.validade $}"/></td>
                                <td><input class="form-control" name="nota" value="{$ x.nota $}"/></td>
                                <td><input class="form-control" name="pedido" value="{$ x.pedido $}"/></td>
                                <td><input class="form-control" name="fornecedor" value="{$ x.fornecedor $}"/></td>
                                <td><input class="form-control" name="dtRecebimento" value="{$ x.recebimento $}"/></td>
                                <td><button class="btn btn-small btn-danger" ng-click="removeItem(x)"><i class="icon-remove"></i></button></td>
                            </tr>
                        </tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="control-group">
                <div class="span5 no-padding">
                    <button type="submit" class="btn btn-sm btn-primary" id="btnSend" ng-click="generateLabels()"><i class="icon-print"></i>  Gerar Etiquetas</button>
                </div>
            </div>
            <span class="ajaxLoading"><img src="{% static 'img/ajax-loader.gif' %}" /></span>
        </div>
    </div>
{% endblock %}

{% block jsLibs %}
    {{ block.super }}
    <script src="{% static 'libs/datatables/js/jquery.datatables.min.js'%}"></script>
{% endblock %}

{% block jsExtra %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/angular.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.10.4.custom.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.ui.combobox.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/custom.combobox.produtos.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.stringify.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/etiqueta_produto.js' %}" ></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#btnCancel').bind('click', function(){
                window.location.href = '{% url "etiqueta.etiqueta_index" %}';
            });
        });
    </script>
{% endblock %}

onyxlog/etiqueta/templates/etiqueta_menu.html
{% extends "layout.html"%}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Início" "/" %}
    {% breadcrumb "Etiquetas" "/etiqueta/" %}
{% endblock %}

{% block breadcrumbrender %}
    {% render_breadcrumbs %}
{% endblock %}

{% block contentDetail %}
    <div class="page-header">
        <h2>{% block title %}Etiquetas{% endblock %}</h2>
        <small>Rotinas de geração de etiquetas de identificação.</small>
    </div>
    <div class="row">
        <ul class="no-padding">
            {% include 'etiqueta_itens_menu.html' %}
        </ul>
    </div>
{% endblock %}